module.exports = {
  docs: [
    'index',
    'faq',
    'avatars',
    'interface',
    'controls',
    {
      type: 'category',
      label: '🌎 World Owners',
      items: [
        'worlds/overview',
        'worlds/performance',
        {
          type: 'category',
          label: 'Apps',
          items: [
            'worlds/apps/audio',
            'worlds/apps/community',
            'worlds/apps/environment',
            'worlds/apps/interaction',
            'worlds/apps/media',
            'worlds/apps/misc',
            'worlds/apps/objects',
            'worlds/apps/tools',
            'worlds/apps/combat',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🎨 Designers',
      items: [
        'designers/overview',
        'designers/avatars',
        'designers/emotes',
        'designers/bloom',
        'designers/optimisation',
        'designers/tags',
        'designers/terrain',
      ],
    },
    {
      type: 'category',
      label: '🖥️ Developers',
      collapsible: true,
      collapsed: true,
      items: [
        'developers/overview',
        'developers/quick-start',
        'developers/structure',
        'developers/react',
        'developers/sync-state',
        'developers/secrets',
        'developers/web3',
        'developers/uploading',
        'developers/destructibles',
        {
          type: 'category',
          label: 'Hooks',
          collapsible: true,
          collapsed: true,
          items: [
            'developers/hooks/use-editing',
            'developers/hooks/use-entity-uid',
            'developers/hooks/use-eth',
            'developers/hooks/use-fields',
            'developers/hooks/use-file',
            'developers/hooks/use-sync-state',
            'developers/hooks/use-world',
          ],
        },
        {
          type: 'category',
          label: 'Components',
          collapsible: true,
          collapsed: true,
          items: [
            'developers/components/app',
            'developers/components/arealight',
            'developers/components/audio',
            'developers/components/background',
            'developers/components/billboard',
            'developers/components/boxes',
            'developers/components/box',
            'developers/components/camera',
            'developers/components/climbing',
            'developers/components/flying',
            'developers/components/gliding',
            'developers/components/global',
            'developers/components/group',
            'developers/components/hdr',
            'developers/components/image',
            'developers/components/input',
            'developers/components/model',
            'developers/components/place',
            'developers/components/pointlight',
            'developers/components/rigidbody',
            'developers/components/skysphere',
            'developers/components/spawn',
            'developers/components/sphere',
            'developers/components/spheres',
            'developers/components/text',
            'developers/components/tonemapping',
            'developers/components/trigger',
            'developers/components/video',
            'developers/components/webview',
          ],
        },
        {
          type: 'category',
          label: 'Utils',
          collapsible: true,
          collapsed: true,
          items: [
            'developers/utils/deg2rad',
            'developers/utils/euler',
            'developers/utils/matrix4',
            'developers/utils/quaternion',
            'developers/utils/rad2deg',
            'developers/utils/randomInt',
            'developers/utils/seed',
            'developers/utils/vector3',
          ],
        },
        {
          type: 'category',
          label: 'Ref',
          collapsible: true,
          collapsed: true,
          items: [
            'developers/ref/avatar-ref',
            'developers/ref/event',
          ],
        },
      ],
    },
  ],
  guides: [
    'guides/overview',
  ],
  developers: [
    'developers/overview',
    'developers/quick-start',
    'developers/structure',
    'developers/react',
    'developers/sync-state',
    'developers/secrets',
    'developers/web3',
    'developers/uploading',
    'developers/destructibles',
    {
      type: 'category',
      label: 'Hooks',
      items: [
        'developers/hooks/use-editing',
        'developers/hooks/use-entity-uid',
        'developers/hooks/use-eth',
        'developers/hooks/use-fields',
        'developers/hooks/use-file',
        'developers/hooks/use-sync-state',
        'developers/hooks/use-world',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        'developers/components/app',
        'developers/components/arealight',
        'developers/components/audio',
        'developers/components/background',
        'developers/components/billboard',
        'developers/components/boxes',
        'developers/components/box',
        'developers/components/camera',
        'developers/components/climbing',
        'developers/components/flying',
        'developers/components/gliding',
        'developers/components/global',
        'developers/components/group',
        'developers/components/hdr',
        'developers/components/image',
        'developers/components/input',
        'developers/components/model',
        'developers/components/place',
        'developers/components/pointlight',
        'developers/components/rigidbody',
        'developers/components/skysphere',
        'developers/components/spawn',
        'developers/components/sphere',
        'developers/components/spheres',
        'developers/components/text',
        'developers/components/tonemapping',
        'developers/components/trigger',
        'developers/components/video',
        'developers/components/webview',
      ],
    },
    {
      type: 'category',
      label: 'Utils',
      items: [
        'developers/utils/deg2rad',
        'developers/utils/euler',
        'developers/utils/matrix4',
        'developers/utils/quaternion',
        'developers/utils/rad2deg',
        'developers/utils/randomInt',
        'developers/utils/seed',
        'developers/utils/vector3',
      ],
    },
    {
      type: 'category',
      label: 'Ref',
      items: [
        'developers/ref/avatar-ref',
        'developers/ref/event',
      ],
    },
  ],
  guides: [
    'guides/overview',
  ],
};
