/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "overview",
    "getting-started",
    "avatars",
    "3d-models",
    {
      type: "category",
      label: "SDK",
      items: [
        "sdk/overview",
        "sdk/quick-start",
        "sdk/structure",
        {
          type: "category",
          label: "API Reference",
          items: [
            {
              type: "category",
              label: "Components",
              items: [
                "sdk/ref/components/app",
                "sdk/ref/components/arealight",
                "sdk/ref/components/audio",
                "sdk/ref/components/background",
                "sdk/ref/components/billboard",
                "sdk/ref/components/box",
                "sdk/ref/components/boxes",
                "sdk/ref/components/camera",
                "sdk/ref/components/climbing",
                "sdk/ref/components/flying",
                "sdk/ref/components/gliding",
                "sdk/ref/components/global",
                "sdk/ref/components/hdr",
                "sdk/ref/components/input",
                "sdk/ref/components/image",
                "sdk/ref/components/model",
                "sdk/ref/components/place",
                "sdk/ref/components/pointlight",
                "sdk/ref/components/rigidbody",
                "sdk/ref/components/skysphere",
                "sdk/ref/components/spawn",
                "sdk/ref/components/sphere",
                "sdk/ref/components/spheres",
                "sdk/ref/components/text",
                "sdk/ref/components/tonemapping",
                "sdk/ref/components/trigger",
                "sdk/ref/components/video",
                "sdk/ref/components/webview",
              ],
            },
            {
              type: "category",
              label: "Hooks",
              items: [
                "sdk/ref/hooks/use-world",
                "sdk/ref/hooks/use-eth",
                "sdk/ref/hooks/use-editing",
                "sdk/ref/hooks/use-fields",
                "sdk/ref/hooks/use-file",
                "sdk/ref/hooks/use-entity-uid",
                "sdk/ref/hooks/use-sync-state",
              ],
            },
            {
              type: "category",
              label: "Utils",
              items: [
                "sdk/ref/utils/deg2rad",
                "sdk/ref/utils/rad2deg",
                "sdk/ref/utils/euler",
                "sdk/ref/utils/matrix4",
                "sdk/ref/utils/quaternion",
                "sdk/ref/utils/vector3",
                "sdk/ref/utils/randomInt",
                "sdk/ref/utils/seed",
              ],
            },
            "sdk/ref/app-config",
            "sdk/ref/avatar-ref",
            "sdk/ref/event",
          ],
        },
        // "sdk/app.json", <-- need to fix this
        "sdk/uploading",
        "sdk/react",
        "sdk/sync-state",
        "sdk/web3",
        "sdk/migration-2.0",
      ],
    },
  ],
};

module.exports = sidebars;
